# 🔢 NumPy — Introduction

**NumPy = Numerical Python**

NumPy is an important Python library for **Data Science, Machine Learning, numerical calculations, arrays, matrices, statistics, and scientific computing**.

The main object in NumPy is the **NumPy Array (`ndarray`)**.

## 1. Why NumPy?

Python lists are general-purpose collections. NumPy arrays are designed for fast numerical operations.

```python
numbers = [10, 20, 30, 40]
print(numbers * 2)
```

Output:

```text
[10, 20, 30, 40, 10, 20, 30, 40]
```

With NumPy:

```python
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr * 2)
```

Output:

```text
[20 40 60 80]
```

NumPy performs the operation on every element.

## 2. Installation

Run in CMD, PowerShell, or a terminal:

```bash
pip install numpy
```

Check the installed version:

```python
import numpy as np
print(np.__version__)
```

> `pip install` is normally run in a terminal, not as regular Python code.

## 3. Importing NumPy

```python
import numpy as np
```

Here:

```text
numpy → library
np    → alias / short name
```

We normally use:

```python
np.array()
np.zeros()
np.ones()
np.mean()
```

In [9]:
import sys

print(sys.executable) 
%pip install numpy

d:\Gen AI\Python\venv\python.exe
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 8.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.3 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 6.8 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 6.8 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 5.9 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 5.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.6 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 4.0 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/

In [4]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## 4. Creating a NumPy Array

Use `np.array()`:

```python
arr = np.array([10, 20, 30, 40])
print(arr)
```

Output:

```text
[10 20 30 40]
```

## 5. 1-D, 2-D and 3-D Arrays

### 1-D

```python
np.array([10, 20, 30, 40])
```

### 2-D

```python
np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

Visual:

```text
1  2  3
4  5  6
```

### 3-D

```python
np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
```

Think of a 3-D array as **multiple 2-D matrices**.

## 6. Important Array Properties

```python
arr.ndim
arr.shape
arr.size
arr.dtype
```

| Property | Meaning |
|---|---|
| `ndim` | Number of dimensions |
| `shape` | Size of each dimension |
| `size` | Total number of elements |
| `dtype` | Data type |

In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


## 7. Indexing

NumPy uses zero-based indexing.

```python
arr = np.array([10, 20, 30, 40])
```

```text
Value:    10   20   30   40
Index:     0    1    2    3
```

Examples:

```python
arr[0]   # 10
arr[2]   # 30
```

### Negative indexing

```python
arr[-1]  # 40
arr[-2]  # 30
```

## 8. 2-D Array Indexing

```python
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
```

To access `50`:

```python
arr[1, 1]
```

General form:

```python
arr[row, column]
```

## 9. Slicing

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
```

Output:

```text
[20 30 40]
```

General form:

```text
[start : stop]
```

The `stop` index is not included.

## 10. NumPy Arithmetic

```python
arr = np.array([10, 20, 30, 40])
```

```python
arr + 5    # [15 25 35 45]
arr - 5    # [ 5 15 25 35]
arr * 2    # [20 40 60 80]
arr / 2    # [ 5. 10. 15. 20.]
```

In [ ]:
arr = np.array([10, 20, 30, 40])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 2)

## 11. Array + Array

Operations can be performed element by element.

```python
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

a + b   # [11 22 33]
a - b   # [ 9 18 27]
a * b   # [10 40 90]
a / b   # [10. 10. 10.]
```

## 12. Mathematical Functions

Important functions:

```python
np.sum(arr)
np.min(arr)
np.max(arr)
np.mean(arr)
np.std(arr)
```

In [ ]:
arr = np.array([10, 20, 30, 40])

print("Sum:", np.sum(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

## 13. Special Array Creation

### `np.zeros()`

```python
np.zeros(5)
```

### `np.ones()`

```python
np.ones(5)
```

### `np.arange()`

```python
np.arange(1, 10)
np.arange(1, 10, 2)
```

### `np.linspace()`

```python
np.linspace(0, 10, 5)
```

In [ ]:
print("Zeros:", np.zeros(5))
print("Ones:", np.ones(5))
print("Arange:", np.arange(1, 10))
print("Arange with step:", np.arange(1, 10, 2))
print("Linspace:", np.linspace(0, 10, 5))

## 14. Random Numbers

### Random decimals

```python
np.random.rand(5)
```

Creates 5 random decimal values between 0 and 1.

### Random integers

```python
np.random.randint(1, 100, 5)
```

Creates 5 random integers from 1 to 99.

In [ ]:
print("Random decimals:", np.random.rand(5))
print("Random integers:", np.random.randint(1, 100, 5))

## 15. Why NumPy is Important for AI/ML

A common Data Science workflow is:

```text
NumPy
  ↓
Pandas
  ↓
Data Cleaning
  ↓
Scikit-learn
  ↓
Machine Learning
```

Many ML concepts are based on:

- Arrays
- Matrices
- Vectors
- Mathematical operations
- Statistics

NumPy gives you the foundation for these concepts.

# 🧠 Quick Revision

```python
import numpy as np

np.array()

arr.ndim
arr.shape
arr.size
arr.dtype

arr[index]
arr[start:stop]

np.sum()
np.min()
np.max()
np.mean()
np.std()

np.zeros()
np.ones()
np.arange()
np.linspace()

np.random.rand()
np.random.randint()
```

### Mental Model

```text
NumPy
 │
 ├── ndarray
 │     ├── 1D
 │     ├── 2D
 │     └── 3D
 │
 ├── Properties
 │     ├── ndim
 │     ├── shape
 │     ├── size
 │     └── dtype
 │
 ├── Indexing & Slicing
 │
 ├── Mathematical Operations
 │
 └── Array Creation
       ├── zeros
       ├── ones
       ├── arange
       └── linspace
```

# 🎯 Practice Questions

### Q1
Create a NumPy array containing:

```text
10, 20, 30, 40, 50
```

Print:
- array
- dimensions
- size
- data type

### Q2
Create this 2-D array:

```text
1  2  3
4  5  6
7  8  9
```

Find:
- shape
- size
- dimensions
- element `5`

### Q3
Create an array from 1 to 20 and find:
- even numbers
- sum
- maximum
- minimum
- mean

### Q4
Create 10 random integers between 1 and 100.

### Q5
Create 5 equally spaced values between 0 and 100 using `np.linspace()`.

## Next Topic

➡️ **NumPy Arrays in Depth**

We will study indexing, slicing, reshaping, `reshape()`, `flatten()`, `ravel()`, axis, row/column operations, joining, splitting, broadcasting, and practice problems.